### ISSUE TITLE
Determine required moodle version and specify in capquiz/version.php

### ISSUE THREAD

**Issue by skrede** [KQMATH/moodle-mod_capquiz#61]
It now "requires" the latest version. CAPQuiz is most certainly compatible with older versions.

**Comment by hgeorgsch** [comment]
I have set up a test server on hasc-moodle3.uials.no running moodle v3.1.4. This is the minimum moodle version in JazzQuiz, and we should test all modules on this server, aiming to use the same requirement for all modules.
I gave up testing on version 3.0 because it is not compatible with PHP 7; it is not worth it.

**Comment by hgeorgsch** [comment]
Tests with v3.1.4 failed with complaints about a missing file.
Tests with v3.2.0 are consistent with behaviour on v3.5.1; i.e. not working, but hopefully fixes on v3.5.1 will make it work on v3.2 too.

**Comment by hgeorgsch** [comment]
Set minimum version to v3.2.  We assume that this works as well as 3.5 and close the issue. We may increase the requirement later if new bugs are detected.
